FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

RUN 
# Copy everything, restore, build and publish
COPY . ./
COPY ./.bindings/*.* .
RUN dotnet publish ./RabbitMQ.Sample.csproj -c Release -o _publish

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app
COPY --from=build-env /app/_publish .
ENTRYPOINT ["dotnet", "RabbitMQ.Sample.dll"]